### PR TITLE
Fixing ELM version from 1.6 to 0.17

### PR DESCRIPTION
**Pull request by shinji62**
Seems now Concourse use elm 0.17 so I just updated contributing.md to reflect it.

### CODE REVIEW

**Comment by vito** [comment]
Ah that should really be 0.17, not 1.7 - looks like it was wrong before too. Mind fixing that along the way?

**Comment by shinji62** [comment]
Will fix that :p

**Comment by shinji62** [comment]
Done.

**Comment by vito** [comment]
thanks, looks good!

**Pull request merged**
