### PR TITLE
Attach callbacks to jobs as well as steps.

### PR DESCRIPTION
**Pull request by jmcarp**
Submitting for feedback before writing tests--lmk if the approach makes sense.

[Resolves https://github.com/concourse/concourse/issues/166]

### CODE REVIEW

**Comment by vito** [comment]
Sweet!

This seems worth of additional testing in [Testflight](https://github.com/concourse/testflight) - probably mirroring the behavior of https://github.com/concourse/testflight/blob/master/pipelines/hooks_test.go

**Comment by vito** [comment]
GitHub's UI is confusing me here. It looks like there's a commit (6d84027) that adds unit tests, but those changes don't show up when looking at the "Files changed" tab.

**Comment by vito** [comment]
Is there anything weird that happens in this case?

```sh
jobs:
- name: double-hooked
  on_failure: ...
  plan:
  - task: x
    on_failure: ...
```

I'm wondering if one of them clobbers the other. Haven't examined the code thoroughly but I could see that happening with certain approaches.

**Comment by jmcarp** [comment]
Sorry, forgot to check in the test somehow--just updated. The test should cover the case that you described. Same goes for the PR against testflight, which is passing locally.

**Comment by vito** [comment]
Ah, so it does. Thanks!

**Comment by jraqula** [comment]
thanks @jmcarp for this contribution! i've merged it into the pipeline and will close this PR.

**Pull request closed without merging**
