### PR TITLE
Create migration for new BTREE index on check_order column of version…

### PR DESCRIPTION
**Pull request by christophermancini**
…_resources table.

This PR replaced https://github.com/concourse/atc/pull/218

### CODE REVIEW

**Comment by vito** [comment]
Looks good, just leaving a comment to kick the CI build and give it another shot. Looks like a flake.

**Comment by vito** [comment]
Dang, looks like I forgot to merge this after kicking the build. Would you mind rebasing to resolve the bindata conflict?

(Note to self: bindata is probably gonna be a pain point for PRs going forward - maybe we should investigate building it in the pipeline instead.)

**Comment by mhuangpivotal** [comment]
Hi @christophermancini, I took the liberty to merge this manually. Thanks!

**Comment by vito** [comment]
We had to roll this back as it caused significant performance issues on our large-scale environment (Wings). We're not 100% sure why, but things perform better without this index. Pretty surprising!

I'm going to capture an optimization for this in concourse/rfcs#1 under the "Implementation Notes" section at the bottom. It'll be even more important once we have the new interface, as it'll be checking across multiple spaces and with many more versions in the history (all of'em).

**Pull request closed without merging**
