### PR TITLE
When many groups are created the page rendering is strange

### PR DESCRIPTION
**Pull request by sambryant4**
### What is it?

When displaying a large number of groups with names that combine to be wider than the page, group names are split over multiple lines and do not render right at all.

This PR is to make the navbar horizontally scrollable while pinning the user menu to the top right at all times.

Re-raising this due to CLA

### CODE REVIEW

**Comment by chendrix** [comment]
Validate that the tests work with changes to the ATC

Verify that bindata.go has been updated.

**Comment by mhuangpivotal** [comment]
We are seeing the horizontal scroll bar always displayed blocking the menu (macOS, Chrome).

image

**Comment by jtarchie** [comment]
The horizontal scroll bar does not work with a mouse scroll wheel, too.

I think this requires more design consultation. I'd like to close this PR in favor of having a discussion with design.

**Comment by jtarchie** [comment]
Discuss here concourse/concourse#946

**Pull request closed without merging**
