### PR TITLE
Credhub Credential Manager

### PR DESCRIPTION
**Pull request by rkoster**
This PR adds Credhub Credential Manager support: [#141798327](https://www.pivotaltracker.com/n/projects/1059262/stories/141798327).
Currently only client credential auth has been implemented. But username password should also be doable to implement.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rkoster Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=183)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/atc&pullRequestId=183) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rkoster Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=183)!

**Comment by rkoster** [comment]
@chendrix I just followed the [vault implementation](https://github.com/concourse/atc/tree/master/creds/vault) which seems to vendor it's own dependencies. Also I'm unable to find the [vault api](https://github.com/concourse/atc/tree/master/creds/vault/vendor/github.com/hashicorp/vault) dependency [in concourse](https://github.com/concourse/concourse/tree/master/src/github.com/hashicorp).

**Comment by jtarchie** [comment]
@rkoster, you're right, it looks like the dependencies were `vendor`ed. I think we just had sticker shock with 900+ files. @chendrix, maybe we should cleanup the vault files.

@rkoster, some of us are not familiar with credhub. Would you be willing to pair on this to walk us through the code?

**Comment by jtarchie** [comment]
@rkoster and I organizing.

**Comment by topherbullock** [comment]
What's the state of this?

Credhub is getting a shiny new go client, which should improve some of the vendoring issues.

**Comment by leungandrew** [comment]
See https://github.com/concourse/atc/pull/194, an implementation using the new CredHub go client.

**Comment by jtarchie** [comment]
@rkoster, thanks for the PR. The credhub team has build a golang library, which made integration a lot easier. We've pulled in their PR #194.

**Pull request closed without merging**
