### PR TITLE
add riemann service prefix

### PR DESCRIPTION
**Pull request by mastertinner**
This PR is a prerequisite for https://github.com/concourse/concourse/pull/602.

### CODE REVIEW

**Comment by vito** [comment]
Mind explaining a bit what the use case for this is? Looks good though (aside from the fact that it no longer merges cleanly - my fault for not getting to it sooner).

**Comment by fdhex** [comment]
As a Riemann server can accept many sources, an optional prefix allows for easier distinction between metrics coming from Concourse vs. metrics coming from other inputs, e.g. using a generic (where (service "#concourse/*") ( ... ))

**Comment by vito** [comment]
Sounds reasonable - thanks!

**Comment by mastertinner** [comment]
Thanks, @vito!

**Pull request merged**
