### PR TITLE
don't hardcode public schema

### PR DESCRIPTION
**Pull request by JamesClonk**
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JamesClonk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=252)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/atc&pullRequestId=252) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by JamesClonk** [comment]
Hardcoding the "public" schema breaks the db migrations when using any other user/schema other than public.
We have our ATC running on a HA postgres deployment, where everything is stored in an "atc" schema.

**Comment by pivotal-issuemaster** [comment]
@JamesClonk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=252)!

**Comment by vito** [comment]
Woops, didn't see this and merged https://github.com/concourse/atc/pull/257 instead. Thanks though!

**Pull request closed without merging**
