### PR TITLE
Set identifying info for check container

### PR DESCRIPTION
**Pull request by zachgersh**
This addresses:

https://github.com/concourse/concourse/issues/258

Hoping that passing external URL around like this is ok. Additionally, tried to pick criteria that would identify a check container - it may be wrong.

Where should the documentation for this feature go?

Signed-off-by: Utako Ueda <uueda@pivotal.io>

### CODE REVIEW

**Comment by robdimsdale** [comment]
@vito @xoebus any thoughts on this PR? What about the question @zachgersh asked - where should documentation for this PR go?

**Comment by zachgersh** [comment]
@vito - any other changes needed here?

**Comment by xoebus** [comment]
No, looks great. Thanks!

**Comment by vito** [comment]
Looking at this again, it's inconsistent with the metadata provided to `/in` and `/out`:

* `BUILD_PIPELINE_NAME` vs. `PIPELINE_NAME`: perhaps it should be `RESOURCE_PIPELINE_NAME`?
* `EXTERNAL_URL` vs. `ATC_EXTERNAL_URL`: this should be `ATC_EXTERNAL_URL`.

**Comment by vito** [comment]
Gonna leave this undocumented for now til that's fixed. /cc @robdimsdale

**Comment by robdimsdale** [comment]
@zachgersh if/when you update these environment variables here, can you also update the `check` user-agent in the pivnet-resource to respect these changes?

**Comment by zachgersh** [comment]
@robdimsdale will do :dancers:

**Pull request merged**
