### PR TITLE
add support for archiving/unarchiving pipelines

### PR DESCRIPTION
**Pull request by tkellen**
Contributes to concourse/concourse#2518.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tkellen Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=300)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/atc&pullRequestId=300) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tkellen Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=300)!

**Comment by vito** [comment]
Heyo, I'm gonna close this out since we're about to archive this repo and transition to the ["one big repo"](https://discuss.concourse-ci.org/t/psa-the-great-code-restructing-of-2018/543/3). Feel free to reopen once the dust has settled! It should at least be much easier to PR after since you won't have to submit 3 times.

Thanks for starting on this! I'll try to sync up on the original issue to get you unblocked as well.

**Comment by tkellen** [comment]
Rad, thanks!

**Pull request closed without merging**
