### PR TITLE
Set cookie headers.

### PR DESCRIPTION
**Pull request by jmcarp**
Allow operators to set `HttpOnly` and `Secure` cookie headers for security / compliance purposes.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jmcarp Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/atc&pullRequestId=138) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jmcarp Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=138)!

**Comment by jmcarp** [comment]
It sounds like you all are going to drop cookie auth entirely, which would make this patch unnecessary. If that's correct, feel free to close this, or let me know so that I can close it.

cc @vito @mariash

**Comment by chendrix** [comment]
Hi there @jmcarp 

We are actually working on a story right this minute (to be released in v2.7.1) that will add this and a bunch of other security around our cookies. Thanks for bringing this to our attention, I'm going to close out this PR!

**Pull request closed without merging**
