### PR TITLE
Fixed #1692 (setting content type on build and job lists)

### PR DESCRIPTION
**Pull request by yevster**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yevster Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=201)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/atc&pullRequestId=201) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@yevster Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=201)!

**Comment by yevster** [comment]
Methinks the CI doth protest too much.

**Comment by vito** [comment]
sorry for the failing CI - it should be fixed now if you rebase.

**Comment by xtremerui** [comment]
Build failed:  https://ci.concourse.ci/builds/429127#L59f9e6fe:39:42

**Comment by vito** [comment]
Closing for now, sorry. Feel free to re-submit though.

**Pull request closed without merging**
