### PR TITLE
Replaces animated pending halo with static pending halo

### PR DESCRIPTION
**Pull request by d**
- This also modifies the legend so that "pending" and "started" are at
  the bottom

Resolves concourse/concourse#987

Signed-off-by: Jesse Zhang <jzhang@pivotal.io>
Signed-off-by: Lindsay Auchinachie <lauchinachie@pivotal.io>

### CODE REVIEW

**Comment by professor** [comment]
This pull request significantly reduces the CPU load for visualizing a concourse pipeline with paused jobs. We've been having issues with our build monitors rendering concourse pipelines.

**Comment by michaelklishin** [comment]
Sounds like a step towards addressing https://github.com/concourse/concourse/issues/991. Thank you so much!

**Comment by ascherbaum-pivotal** [comment]
+1 to anything which let's the fan in my laptop not spinning at full speed!

**Comment by gerhard** [comment]
:shipit: pls

**Comment by jtarchie** [comment]
@d, can I ask for two things?

* An example of the high CPU usage with the animation.
* And a screenshot showing that it decreased.

**Comment by professor** [comment]
Here is the hack day demo explaining the change:
https://drive.google.com/a/pivotal.io/file/d/0B9ljoEuCdXaxd0JkVUF0elA5WjQ/view?usp=sharing

@jtarchie
before the change:
Tab: 75%, GPU Process: 27%

after the change: 
Tab: 18%, GPU Process: 10%

(Note that it is difficult for me to apply the change to our production pipeline, so the 'after' number is an estimate based on the change. When we made the Hack Day demo we saw a clear reduction in CPU utilization, but we didn't write down the exact numbers.)

before_change

after_change

**Comment by mhuangpivotal** [comment]
This looks good. Thanks for the PR!

**Comment by jtarchie** [comment]
Awesome!

**Pull request merged**
