### PR TITLE
Export request latency and worker metrics.

### PR DESCRIPTION
**Pull request by jmcarp**
WDYT @vito @TimSimmons ?

### CODE REVIEW

**Comment by vito** [comment]
looks good to me! guessing you tried it out?

**Comment by jmcarp** [comment]
Yep! Worker metrics look like this:

```
# HELP concourse_workers_containers Number of containers per worker
# TYPE concourse_workers_containers gauge
concourse_workers_containers{worker="3db373c680c2"} 5
```

And request latencies like this:

```
# HELP concourse_http_responses_duration_seconds Response time in seconds
# TYPE concourse_http_responses_duration_seconds histogram
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.005"} 0
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.01"} 0
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.025"} 0
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.05"} 0
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.1"} 0
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.25"} 1
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="0.5"} 1
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="1"} 1
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="2.5"} 1
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="5"} 1
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="10"} 1
concourse_http_responses_duration_seconds_bucket{method="GET",path="/",le="+Inf"} 1
concourse_http_responses_duration_seconds_sum{method="GET",path="/"} 0.141298
concourse_http_responses_duration_seconds_count{method="GET",path="/"} 1
...
```

**Comment by TimSimmons** [comment]
This looks good to me :+1:

**Comment by vito** [comment]
thanks!

**Pull request merged**
