### PR TITLE
Use Kubernetes secrets as a credential manager

### PR DESCRIPTION
**Pull request by william-tran**
Address PR feedback in #189. 

- Lookup secrets with the same heuristic used in Vault.
- Use a prefix for namespaces to avoid collisions. (default: concourse-)

Testing locally:
1. Get `kubectl` to target a cluster.
1. Edit concourse/dev/atc (or concourse/dev/atc-dockerdb) and add `--kubernetes-config-path=[userhome]/.kube/config` to the command line flags.
1. `./dev/start`
1. `fly -t lite sp -p hello-world -c hello-world.yml` with the following pipeline:

    ```
    jobs:
    - name: hello-world
      plan:
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine}
          params:
            SECRET: ((my-secrets.secret1))
          run:
            path: /bin/sh
            args: ["-c", "echo $SECRET"]

1. Run the pipeline and see an error in the UI `Expected to find variables: my-secrets`. Also see a log message `k8s-secret-not-found` with data about the namespace and secrets that were searched for. 
1. `kubectl create namespace concourse-main`
1. `kubectl config set-context $(kubectl config current-context) --namespace=concourse-main`
1. `kubectl create secret generic hello-world.my-secrets --from-literal "secret1=secretvalue1"`
1. Run the pipeline and see `secretvalue1` printed.
1. `kubectl delete secret  hello-world.my-secrets`
1. `kubectl create secret generic my-secrets --from-literal "secret1=secretvalue2"`
1. Run the pipeline and see `secretvalue2` printed.
1. `kubectl create secret generic my-secret-value --from-literal "value=secretvalue3"`
1. Change `((my-secrets.secret1))` to `((my-secret-value))` in the pipeline.
1. Run the pipeline and see `secretvalue3` printed.

### CODE REVIEW

**Comment by william-tran** [comment]
ping @vito @topherbullock

**Comment by william-tran** [comment]
I force pushed a change to improve logging and added more verification steps. I'm good with this now.

**Comment by farcaller** [comment]
LGTM

**Comment by vito** [comment]
Thanks! Taking a look at this now.

One quick note: we're moving away from vendoring dependencies, in favor of just submoduling them in our BOSH release repo as we do for the rest of our dependencies. See #216 for more context. I can strip out that commit myself though.

**Comment by vito** [comment]
merged, and bumped in https://github.com/concourse/concourse/commit/fa0fc33da5e642b97c00824ebef86fbee81bd46a - thanks!

**Pull request closed without merging**
