### PR TITLE
Interpolate webhook_token values from cred source

### PR DESCRIPTION
**Pull request by timrchavez**
A `webhook_token` should be considered a secret and have the ability to
receive its value from a cred source like Vault.

### CODE REVIEW

**Comment by timrchavez** [comment]
I plugged the dev atc (`dev/atc-dockerdb`) into a devel vault instance for additional testing (btw, we may want to include a `dev/docker-vault` thing in `dev/` to test cred interpolation things)...

*pipeline config*
```
18:27 $ ./fly -t main gp -p webhook-interpolation-test
groups: []
resources:
- name: concourse
  webhook_token: ((webhook_token))
  type: pull-request
  source:
    repo: timrchavez/concourse
    uri: git@github.com:timrchavez/concourse.git
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
jobs:
- name: tests
  public: true
  plan:
  - get: concourse
    trigger: true
    version: every
```

*vault secret*
```
18:32 $ vault read /concourse-training/main/webhook_token
Key             	Value
---             	-----
refresh_interval	768h0m0s
value           	abcde12345
```
*webhook called with valid secret*
```
18:32 $ curl -I -X POST http://127.0.0.1:8080/api/v1/teams/main/pipelines/webhook-interpolation-test/resources/concourse/check/webhook?webhook_token=abcde12345
HTTP/1.1 200 OK
X-Concourse-Version: 0.0.0-dev
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Date: Tue, 24 Apr 2018 23:33:14 GMT
Content-Length: 0
```

*webhook called with invalid secret*
```
18:33 $ curl -I -X POST http://127.0.0.1:8080/api/v1/teams/main/pipelines/webhook-interpolation-test/resources/concourse/check/webhook?webhook_token=abcde123456
HTTP/1.1 401 Unauthorized
X-Concourse-Version: 0.0.0-dev
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Date: Tue, 24 Apr 2018 23:34:17 GMT
Content-Length: 0
```

*deleted secret*
```
18:35 $ curl -I -X POST http://127.0.0.1:8080/api/v1/teams/main/pipelines/webhook-interpolation-test/resources/concourse/check/webhook?webhook_token=abcde12345
HTTP/1.1 401 Unauthorized
X-Concourse-Version: 0.0.0-dev
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Date: Tue, 24 Apr 2018 23:37:13 GMT
Content-Length: 0

18:37 $ curl -I -X POST http://127.0.0.1:8080/api/v1/teams/main/pipelines/webhook-interpolation-test/resources/concourse/check/webhook?webhook_token=\(\(webhook_token\)\)
HTTP/1.1 200 OK
X-Concourse-Version: 0.0.0-dev
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Xss-Protection: 1; mode=block
Date: Tue, 24 Apr 2018 23:38:11 GMT
Content-Length: 0
```

**Comment by timrchavez** [comment]
Note the last test I performed after deleting the secret. If you do not provide a value to interpolate your `webhook_token` variable with, your `webhook_token` value will literally be whatever the variable label is... e.g. ((webhook_token)). This may not be a _huge_ security concern, but technically, if there's no interpolation happening, if someone guessed correctly at the label or had access to the pipeline config, they could then force your pipeline resource to check. Not sure if that could be used in a DoS attack or something, but maybe worth noting?

**Comment by pivotal-jwinters** [comment]
@timrchavez It might be nice if we could have a more generic `string` credential instead of one specifically for webhook tokens. Thoughts?

**Comment by pivotal-jwinters** [comment]
@timrchavez I'm not suggesting we change anything about when/how it gets interpolated, just a more generically named interpolator. Like `creds.String` or `creds.Value`. Just so we don't end up with a different interpolator for every credential we may want to interpolate.

```
token, err := creds.NewString(variables, pipelineResource.WebhookToken()).Evaluate()
```

**Comment by timrchavez** [comment]
Ah! I see now

**Comment by timrchavez** [comment]
@pivotal-jwinters I've implemented the change you suggested. Thanks for the review!

**Comment by pivotal-jwinters** [comment]
@timrchavez Looks good. Thanks!

**Pull request merged**
