### PR TITLE
GitLab OAuth integration

### PR DESCRIPTION
**Pull request by markstgodard**
Hi @vito 

As per discussion today in Slack regarding adding GitLab OAuth integration:

- Registers a new gitlab oauth provider
- Provides support to authorize team members based on GitLab Groups
- New flags for GitLab auth include:
      --gitlab-auth-client-id
      --gitlab-auth-client-secret
      --gitlab-auth-group
      --gitlab-auth-auth-url
      --gitlab-auth-token-url
      --gitlab-auth-api-url

- gitlab-auth-group flag may be specified more than once to associate with
multiple GitLab groups

**NOTE: This change also requires adding new package: github.com/xanzy/go-gitlab to concourse GOPATH** 
**UPDATE: Talked to @vito, vendoring into auth provider**

Also let me know if you want me to submit a PR for the changes to fly CLI as well.
**UPDATE: Talked to @vito, fly gets from atc**

I have tested this out with our GitLab deployment using its v4 API and it works well.
Let me know if you need any updates to the PR.

Cheers

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@markstgodard Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=172)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/atc&pullRequestId=172) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@markstgodard Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/atc&pullRequestId=172)!

**Comment by markstgodard** [comment]
Hi @vito 

Thanks, I updated tests and vendored into gitlab provider.

Have a review and let me know if you want me to squash commits.

Cheers

**Comment by Chumper** [comment]
I would like to add the token option as well to the gitlab provider, which means to update #169 and base it on this branch.

**Comment by mariash** [comment]
Thanks for PR! It looked good!

**Pull request merged**
